title: jekyll_blog
email: efm22104@kwansei.ac.jp
description: This is keigo's blog
baseurl: "/my_jekyll"
url: "http://keigo789.github.io" # the base hostname & protocol for your si                      
github_username:  keigo789
markdown: kramdown
lang: ja-JP                                                                     
#minimal_mistakes_skin: dark                                                                        
theme: jekyll-theme-cayman
plugins:
  - github-pages
  - jekyll-feed
  - jekyll-org

permalink: /:categories/:short_year-:month-:day/:title

sass:
sass_dir: _sass
style: compressed
#lsi: true                                                                                          
# exclude:                                                                                         
#   - Gemfile                                                                                      
#   - Gemfile.lock                                                                                 
#   - node_modules                                                                                 
#   - vendor/bundle/                                                                               
#   - vendor/cache/                                                                                
#   - vendor/gems/                                                                                 
#   - vendor/ruby/  

